[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pdas = "GY13uFJVb5fMTkUe6w44CSu8ZEF5UadLsrTXZanCe4eM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/VikramR/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
